### ISSUE TITLE
Store selected sources

### ISSUE THREAD

**Issue by asbjornenge** [meanwhile-news/meanwhile-app#2]
Localstorage er vel midt i blinken til det? Burde kanskje indikert "source" ikonet med en annen farge dersom noe var valgt?

//cc @megatrond

**Comment by megatrond** [comment]
Frem til vi har innlogging fyrer vi det i localstorage, så kan vi ha localstorage som en cache når vi har innlogging og serverlagring?

**Comment by asbjornenge** [comment]
:+1: jeg tar denne med en gang jeg :-)
